#!/bin/bash
#
# km3test - startup file
#

# MYSQL
[ -z "$KM3TEST_NOMYSQL" ] &&\
   mysqld_safe --basedir=/usr --datadir=/var/lib/mysql &

# SSH on 2222 port
[ -z "$KM3TEST_NOSSH" ] &&\
   /usr/sbin/sshd -p 2222 -D &

# NTP
mv /etc/ntp.conf /etc/ntp.conf_ntp &&\
echo "driftfile /var/lib/ntp/drift" >/etc/ntp.conf &&\
echo "restrict 127.0.0.1" >>/etc/ntp.conf &&\
echo "restrict ::1" >>/etc/ntp.conf &&\
echo "restrict $DOMNET mask $DOMNETMASK nomodify notrap" >>/etc/ntp.conf &&\
echo "server $NTP_HOST iburst" >>/etc/ntp.conf

[ "$NTP_HOST" != "192.168.1.1" ] &&\
    sed -i 'env' s/^server.*/server\ "$NTP_HOST"/ /etc/ntp.conf
[ -z "$KM3TEST_NONTP" ] &&\
   /usr/sbin/ntpd -g -p /var/run/ntpd.pid -l /var/log/ntpd

# DHCP
[ ! -d /etc/dhcp ] &&\
  mkdir -p /etc/dhcp &&
[ ! -f /etc/dhcp/dhcpd.conf ] &&\
  echo "default-lease-time 600;" >/etc/dhcp/dhcpd.conf &&\
  echo "max-lease-time 7200;" >>/etc/dhcp/dhcpd.conf &&\
  echo "ddns-update-style none;" >>/etc/dhcp/dhcpd.conf &&\
  echo "authoritative;" >>/etc/dhcp/dhcpd.conf &&\
  echo "" >>/etc/dhcp/dhcpd.conf &&\
  echo "# keep this line unchanged! it is needed for a proper working new_dom.py script" >>/etc/dhcp/dhcpd.conf &&\
  echo "" >>/etc/dhcp/dhcpd.conf &&\
  echo "subnet $DOMNET netmask $DOMNETMASK {" >>/etc/dhcp/dhcpd.conf &&\
  echo "  range dynamic-bootp $DOMNET_DHCP_FROM $DOMNET_DHCP_TO;" >>/etc/dhcp/dhcpd.conf &&\
  echo "}" >>/etc/dhcp/dhcpd.conf

# Configure a new DHCP service, using variables:
#     WRSMAC MAC address of the white rabbit switch
#     WRSIP IP address assigned to white rabbit switch
#     ISWMAC MAC address of the intermediate switch between test PC and WRS network
#     DHCPDIF Interface name connected to WRS network
[ -z "$WRSMAC" ] &&\
  [ -z "$KM3TEST_NODHCPD" ] &&\
    echo "WARNING: No WRS MAC address specified, please verify generated DHCPD configuration"
[ -z "$WRSIP" ] &&\
  [ -z "$KM3TEST_NODHCPD" ] &&\
    WRSIP=${DOMNET%.*}.251
    echo "WARNING: No WRS IP address specified, using default address: $WRSIP in DHCPD configuration"
 
if [ -n "$WRSMAC" ]; then
  # Sometime WRS has an intermediate switch, configure it as well if necessary
  if [ -n "$ISWMAC" ]; then
    [ -z "$ISWIP" ] &&\
      ISWIP=${DOMNET%.*}.251
      echo "WARNING: Intermediate WR switch IP not specified, using default: $ISWIP"
    ISDHCPCONF='# Intermediate switch (link between Test host and WRS)
host isw {
  hardware ethernet '${ISWMAC}';
  fixed-address '${ISWIP}';
}'
  fi
  #  The script assumes the WRS management belongs to the DOM network segment as well
  #  Using an intermediate switch (ISWMAC). Use any value if no ISWMAC is present.
  [ ! -f /etc/dhcp/dhcpd.conf ] &&\
    cat <<EOF >/etc/dhcp/dhcpd.conf
default-lease-time 600;
max-lease-time 7200;
ddns-update-style none;
authoritative;
#WRS (fix IP for WRS management)
host wrs {
  hardware ethernet ${WRSMAC};
  fixed-address ${WRSIP};
}
${ISDHCPCONF}

# keep this line unchanged! it is needed for a proper working new_dom.py script

subnet ${DOMNET} netmask ${DOMNETMASK} {
  range dynamic-bootp ${DOMNET_DHCP_FROM} ${DOMNET_DHCP_TO}
}
EOF
fi

[ -z "$KM3TEST_NODHCPD" ] &&\
  [ "$DHCPDIF" != "" ] &&\
    dhcpd -4 -f -d --no-pid -cf /etc/dhcp/dhcpd.conf "$DHCPDIF" 2>/var/log/messages >/var/log/messages

echo "Started km3test"
touch .km3test 
while [ -f .km3test ]; do
  sleep 3600
done
echo "Terminated km3test"
